@host = http://localhost:5102

### Login
# @name login
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "userName": "Victor",
    "password": "your_password_here"
}

### 
@accessToken = {{login.response.body.accessToken}}
@refreshToken = {{login.response.body.refreshToken}}