<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Commands\Login\" />
    <Folder Include="Features\Auth\Commands\Register\" />
    <Folder Include="Features\Auth\Queries\" />
  </ItemGroup>

</Project>
