@host = http://localhost:5102

### Reset Password
POST {{host}}/api/auth/reset-password
Content-Type: application/json

{
    "token": "YOUR_PASSWORD_RESET_TOKEN_HERE",
    "newPassword": "NewSecurePassword123!"
}
